before_script:
  - npm install; npm install -g gulp; npm install gulp-mocha gulp-util chai;
script: gulp lt
notifications:
  email: false
language: node_js
env:
  - PORT=7777
node_js:
  - "6.3"
  - "4"